- name: RuuviTag_Keittio_Temperature
  state_topic: "RuuviPublisherData/Keittio"
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_template: "{{ value_json.temperature|float|round(1) }}"
- name: RuuviTag_Keittio_Humidity
  state_topic: "RuuviPublisherData/Keittio"
  unit_of_measurement: "%"
  device_class: "humidity"
  value_template: "{{ value_json.humidity|float|round(1) }}"