- name: "PajaKylma"
  state: "{{ states('sensor.ruuvitag_paja_temperature') | float(default=0.0) < 7.0 }}"
- name: "MajaKylma"
  state: "{{ states('sensor.ruuvitag_maja_temperature') | float(default=0.0) < 7.0 }}"
- name: "PajaLammin"
  state: "{{ states('sensor.ruuvitag_paja_temperature') | float(default=0.0) > 13.0 }}"
- name: "MajaLammin"
  state: "{{ states('sensor.ruuvitag_maja_temperature') | float(default=0.0) > 13.0 }}"