version: "3"

networks:
  metrics:
    external: false

services:
  influxdb:
    image: influxdb:2.1
    container_name: influxdb
    restart: always
    networks: [metrics]
    ports:
      - "8086:8086"
    volumes:
      - $HOME/Talonvalvonta/docker/influxdb/data:/var/lib/influxdb2
      - $HOME/Talonvalvonta/docker/influxdb/influxdb.conf:/etc/influxdb2/influxdb.conf:ro
      - $HOME/Talonvalvonta/docker/influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME} # sourced from .env
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_USERPWD_ADMIN} # sourced when starting the container
      - DOCKER_INFLUXDB_INIT_ORG=Talonvalvonta
      - DOCKER_INFLUXDB_INIT_BUCKET=Talonvalvonta-Bucket
      - INFLUXDB_USERPWD_TELEGRAF=${INFLUXDB_USERPWD_TELEGRAF}
      - INFLUXDB_USERPWD_GRAFANA=${INFLUXDB_USERPWD_GRAFANA}
  telegraf:
    image: telegraf:1.21
    restart: always
    container_name: telegraf
    networks: [metrics]
    volumes:
      - $HOME/Talonvalvonta/docker/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUXDB_USERPWD_TELEGRAF=${INFLUXDB_USERPWD_TELEGRAF}
