version: "3.3"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "1000" # needs to be `id -u` // alternatively chown the grafana/data dir to 472:472
    ports:
      - "3000:3000" # expose for localhost
    volumes:
      - $HOME/Talonvalvonta/docker/grafana/data:/var/lib/grafana # data path
      - $HOME/Talonvalvonta/docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - $HOME/Talonvalvonta/docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
