version: "3.3"

networks:
  metrics:
    external: true
    name: influxdb_metrics

services:
  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    networks: [metrics]
    restart: always
    user: "1000" # needs to be `id -u` // alternatively chown the grafana/data dir to 472:472
    ports:
      - "3000:3000" # expose for localhost
    volumes:
      - $HOME/Talonvalvonta/docker/grafana/data:/var/lib/grafana # data path
      - $HOME/Talonvalvonta/docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - $HOME/Talonvalvonta/docker/grafana/provisioning:/etc/grafana/provisioning
      - $HOME/Talonvalvonta/docker/grafana/dashboards:/var/lib/grafana_dashboards
      - $HOME/Talonvalvonta/docker/grafana/custom_plugins:/custom_plugins
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,/custom_plugins/mqtt-datasource.zip;mqtt-datasource
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - INFLUX_TOKEN=${INFLUXDB_GRAFANA_TOKEN}
      - GRAFANA_DISCORD_NOTIFIER_WEBHOOK=${GRAFANA_DISCORD_NOTIFIER_WEBHOOK}
