version: "3.9"

networks:
  metrics:
    external: true
    name: influxdb_metrics

services:
  energy-pulse-reader:
    privileged: true
    networks: [metrics]
    image: energy-pulse-reader:latest
    restart: always
    container_name: energy-pulse-reader
    volumes:
      - $HOME/Talonvalvonta/docker/EnergyPulseReader/energypulsereader.ini:/pulsereader/energypulsereader.ini:ro