{
 "title": "Perusnäyttö",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "RuuviTags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Huonelämpötilat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ruuvi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ruuvi_measurements\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Huonekosteudet",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"ruuvi\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ruuvi_measurements\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Energiakulutus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Hetkellinen kulutus",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "queryText": "EnergyPulseReaderData" }
   ]
  },
  {
   "title": "Tänään",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energypulsereader\")\r\n  |> range(start: duration(v: uint(v: today()) - uint(v: now())), stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricity_15min_kWh\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Päiväkulutus (7pvä)",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"strings\"\r\nimport \"experimental\"\r\n\r\n// Query energy readings back -X days from current day. Takes current time in to account and returns full days back and current day up until current time.\r\n// -0d means only today, -1d means today and yesterday etc.\r\nfrom(bucket: \"energypulsereader\")\r\n  |> range(start: duration(v: uint(v: experimental.addDuration(d: -7d, to: today())) - uint(v: now())), stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricity_15min_kWh\")\r\n  |> aggregateWindow(every: 1d, offset: -1s, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with date: strings.substring(v: string(v: date.truncate(t: r._time, unit: 1d)), start: 0, end: 10) }))"
    }
   ]
  },
  {
   "title": "Kuukausikulutus (kuluva)",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"strings\"\r\nimport \"experimental\"\r\n\r\n// Query energy readings back -X months from current day. Takes current day/time in to account and returns full months back and current month up until current time.\r\n// -0mo means only current month, -1d means this month and previous etc.\r\nfrom(bucket: \"energypulsereader\")\r\n  |> range(start: duration(v: uint(v: experimental.addDuration(d: -0mo, to: date.truncate(t: today(), unit: 1mo))) - uint(v: now())), stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricity_15min_kWh\")\r\n  |> aggregateWindow(every: 1mo, offset: -1s, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with date: strings.substring(v: string(v: date.truncate(t: r._time, unit: 1mo)), start: 0, end: 7) }))"
    }
   ]
  },
  { "title": "Telegraf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ _value: if r._value > 86400 then string(v: r._value / 86400) + \" d\" else string(v: r._value / 3600) + \" h\" }))\r\n "
    }
   ]
  },
  {
   "title": "CPU Idle %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rpi_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")  "
    }
   ]
  },
  {
   "title": "CPU Freq",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rpi_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"freq\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")  "
    }
   ]
  },
  {
   "title": "MEM Usage %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"/etc/hosts\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}