saunavalmis:
  name: SaunaValmis
  entity_id: binary_sensor.saunavalmis
  repeat: 120
  can_acknowledge: false
  skip_first: false
  message: "Sauna on valmis!"
  notifiers: discord_notify_alert_group