apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    secureJsonData:
      token: $INFLUX_TOKEN
    jsonData:
      version: Flux
      organization: Talonvalvonta
      defaultBucket: telegraf
      tlsSkipVerify: true