apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    isDefault: true
    access: proxy
    database: telegraf
    user: grafana
    url: http://localhost:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: $INFLUXDB_USERPWD_GRAFANA
