- name: RuuviTag_MatiaksenHuone_Temperature
  state_topic: "RuuviPublisherData/MatiaksenHuone"
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_template: "{{ value_json.temperature|float|round(1) }}"
- name: RuuviTag_MatiaksenHuone_Humidity
  state_topic: "RuuviPublisherData/MatiaksenHuone"
  unit_of_measurement: "%"
  device_class: "humidity"
  value_template: "{{ value_json.humidity|float|round(1) }}"